version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9567/_cluster/health || exit 1"]
      interval: 3s
      retries: 10
    volumes:
      - root_esdata:/usr/share/elasticsearch/data

  fastapi:
    build: ./backend
    container_name: fastapi2
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ES_HOST=http://elasticsearch:9567
    networks:
      - mynetwork
    ports:
      - "9567:9567"
      
networks:
  mynetwork:
    driver: bridge

volumes:
  root_esdata: